# Generated by Django 6.0 on 2026-01-19 10:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_name', models.CharField(max_length=100)),
                ('food_type', models.CharField(choices=[('veg', 'Veg'), ('non-veg', 'Non-Veg')], max_length=10)),
                ('quantity', models.CharField(max_length=50)),
                ('expiry_time', models.DateTimeField()),
                ('pickup_address', models.TextField()),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('available', 'Available'), ('requested', 'Requested'), ('completed', 'Completed')], default='available', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
