# Generated by Django 6.0 on 2026-01-26 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='food_category',
            field=models.CharField(choices=[('cooked', 'Cooked Food'), ('packed', 'Packed Food'), ('raw', 'Raw Ingredients')], default='cooked', max_length=20),
        ),
    ]
