# Generated by Django 6.0 on 2026-01-28 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodrequest',
            name='receiver_location',
            field=models.TextField(blank=True),
        ),
    ]
