# Generated by Django 6.0 on 2026-01-28 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0002_foodrequest_receiver_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodrequest',
            name='receiver_location',
            field=models.TextField(),
        ),
    ]
